version: "3.3"

services:
  db:
    image: postgres:13.1
    container_name: music-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./dockerfiles/postgresql/data:/var/lib/postgresql/data
    restart: on-failure